### ISSUE TITLE
authentication is required for each unplugging android device

### ISSUE THREAD

**Issue by liaoqingmo** [smaeul/android-tools#2]
Runing on OpenWrt(mips,big endian CPU) successfully,but every time I unplug an Android phone, the dialog box "Whether USB debugging is allowed" pops up.Do you have any idea about this issue?(ps:sorry,my english is poor)

**Comment by liaoqingmo** [comment]
Detailed log file here is [https://whycan.cn/files/members/1237/adb-log.rar](url)

**Comment by liaoqingmo** [comment]
Detailed log file here ：[adb-log.zip](https://github.com/smaeul/android-tools/files/4971726/adb-log.zip)
Looking forward to your reply,thanks!

**Comment by smaeul** [comment]
Unfortunately, you're going to have a really bad time running on a big-endian machine. I patched adb just enough for my needs at the time -- there are a lot more places that assume a little-endian CPU. I don't have the resources to help further at this time, sorry.

**Comment by liaoqingmo** [comment]
Okay,thanks for your good job and reply! It seem that the publickey is not create correctly about the issue I submitted.I will try to debug it. God bless me.

---Original---
